//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Suggestion.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Bb.Suggestion.SuggestionParser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SuggestionParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ISuggestionVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.sql_stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_stmt_list([NotNull] SuggestionParser.Sql_stmt_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.sql_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_stmt([NotNull] SuggestionParser.Sql_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.select_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_stmt([NotNull] SuggestionParser.Select_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.where_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_stmt([NotNull] SuggestionParser.Where_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] SuggestionParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_literal([NotNull] SuggestionParser.Numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.bind_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBind_parameter([NotNull] SuggestionParser.Bind_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_literal([NotNull] SuggestionParser.String_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] SuggestionParser.Function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.any_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_name([NotNull] SuggestionParser.Any_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.binary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_operator([NotNull] SuggestionParser.Binary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator([NotNull] SuggestionParser.Unary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SuggestionParser.literal_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral_value([NotNull] SuggestionParser.Literal_valueContext context);
}
} // namespace Bb.Suggestion.SuggestionParser
